version: 2
jobs:
  test-3.6: &full-test-template
    docker:
      - image: circleci/python:3.6-jessie

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: install dependencies
          command: |
            python -m virtualenv env
            . env/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}
        
      - run:
          name: run tests
          command: |
            . env/bin/activate
            coverage run -m unittest discover

      - run:
          # requires COVERALLS_REPO_TOKEN env variable
          name: coveralls
          command: |
            . env/bin/activate
            coveralls

      - run:
          name: doctest
          command: |
            . env/bin/activate
            make -C docs/ doctest

  test-3.5:
    <<: *full-test-template
    docker:
      - image: circleci/python:3.5-jessie

  test-3.4:
    <<: *full-test-template
    docker:
      - image: circleci/python:3.4-jessie

  test-2.7:
    <<: *full-test-template
    docker:
      - image: circleci/python:2.7-jessie

workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-2.7
      - test-3.5
      - test-3.4
